image: node:11-alpine

stages:
  - lint
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

run development linter:
  stage: lint
  variables:
    NODE_ENV: "development"
  except:
    - master
    - dev
  before_script:
   - npm install
  script:
    - npm run lint

run production linter:
  stage: lint
  variables:
    NODE_ENV: "production"
  only:
    - master
    - dev
  before_script:
   - npm install
  script:
    - npm run lint
    
build site:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy site:
  stage: deploy
  only:
    - master
    - dev
  cache: {}
  script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$NETMOBIEL_SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -a --delete -e "ssh -o StrictHostKeyChecking=no" dist/* gitlab@dev.netmobiel.eu:/var/www/netmobiel-view-client

