image: node:11-alpine

stages:
  - lint
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

run development linter:
  stage: lint
  variables:
    NODE_ENV: "development"
  except:
    - master
    - dev
  before_script:
   - npm install
  script:
    - npm run lint

run production linter:
  stage: lint
  only:
    - master
    - dev
  before_script:
   - npm install
  script:
    - npm run lint-prod

build site acceptance:
  stage: build
  environment:
    name: acceptance
    url: https://acc.netmobiel.eu
  only:
    - dev
  script:
    - apk update && apk add git
    - hash=`git describe --always`
    - echo $hash > src/assets/current.hash
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy site acceptance:
  stage: deploy
  environment:
    name: acceptance
    url: https://acc.netmobiel.eu
  only:
    - dev
  cache: {}
  script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$NETMOBIEL_ACC_SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -a --delete -e "ssh -o StrictHostKeyChecking=no" dist/* gitlab@acc.netmobiel.eu:/var/www/netmobiel-view-client

build site production:
  stage: build
  environment:
    name: production
    url: https://app.netmobiel.eu
  only:
    - master
  script:
    - apk update && apk add git
    - hash=`git describe --always`
    - echo $hash > src/assets/current.hash
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy site production:
  stage: deploy
  environment:
    name: production
    url: https://app.netmobiel.eu
  when: manual
  only:
    - master
  cache: {}
  script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$NETMOBIEL_SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -a --delete -e "ssh -o StrictHostKeyChecking=no" dist/* gitlab@app.netmobiel.eu:/var/www/netmobiel-view-client
