image: node:11

stages:
  - lint
  - build
  - test
  - deploy

run linter:
  stage: lint
  only:
    refs:
      - dev
      - master
      - /*pull*/
  script:
    - npm install --progress=false
    - npm run lint

build site:
  stage: build
  only:
    refs:
      - dev
      - master
      - merge_requests
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist