stages:
  - lint
  - build
  - test
  - deploy

run linter:
  image: node:11
  stage: lint
  script:
    - npm install
    - NODE_ENV=production npm run lint

build site:
  image: node:8
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist