image: node:11-alpine

stages:
  - lint
  - build
  - test
  - deploy

run linter:
  stage: lint
  script:
    - npm install --progress=false
    - npm run lint

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy site:
  stage: deploy
  script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$NETMOBIEL_SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ls
    - scp -r -o StrictHostKeyChecking=no dist gitlab@dev.netmobiel.eu:~/html
